### ISSUE TITLE
Video editing/encoding progress events are not being delivered

### ISSUE THREAD

**Issue by nvahalik** [dragermrb/capacitor-plugin-video-editor#10]
Testing on iOS. We have added this to our project:

    VideoEditor.addListener('transcodeProgress', (result) => {
      this.ngZone.run(() => {
        console.log('transcodeProgress', result);
        this.transcodeProgress.message = `Processing... ${(result.progress * 100).toFixed(0)}%`;
      });
    });

However, we are not getting any messages.

Further review of the code indicates that the progress indicator is not actually wired up. The `progressHandler` is defined and passed in, but in the actual implementation the `progressHandler` is never called.

**Comment by dragermrb** [comment]
Hi!

I'm on vacation for two weeks, I'll look at it when I get back

**Comment by nvahalik** [comment]
@dragermrb No worries! I've submitted a PR that adds the functionality.

I'm not sure if the approach we've taken is the best, but it at least provides a starting place.

**Comment by dragermrb** [comment]
Thanks @nvahalik 

Merged #11
