### ISSUE TITLE
Android: mimeType only set if generated URI has the content scheme

### ISSUE THREAD

**Issue by nvahalik** [dragermrb/capacitor-plugin-video-editor#14]
See: https://github.com/dragermrb/capacitor-plugin-video-editor/blob/217375006b2984bea3ce386ec3f86373ca4c0ad9/android/src/main/java/com/whiteguru/capacitor/plugin/videoeditor/VideoEditorPlugin.java#L226

In our case, the URI being generated begins with `file://` and so the type is never set.

<img width="745" alt="image" src="https://github.com/dragermrb/capacitor-plugin-video-editor/assets/632120/14ffa702-a8ad-41f7-b43a-4079bca37b57">

**Comment by dragermrb** [comment]
Merged and released

Thanks @nvahalik
