### ISSUE TITLE
iOS thumbnail always square

### ISSUE THREAD

**Issue by CricketLaChica** [dragermrb/capacitor-plugin-video-editor#17]
On iOS, the `thumbnail` function always results in a square aspect ratio. I noticed on `VideoEditor.swift`, line 111, width and height are being set to the same variable. Could this be made in error? In the Android files, it's implemented properly.

**Comment by CricketLaChica** [comment]
When I change the aspect ratio to something that’s not a square, the thumbnail ends up being distorted. Anyone else having this issue? It happens to me on iOS.

**Comment by dragermrb** [comment]
I'll probably fix it next week.

**Comment by CricketLaChica** [comment]
@dragermrb Thank you sir!

**Comment by dragermrb** [comment]
You need to fix `cropToBound()` function:
https://github.com/dragermrb/capacitor-plugin-video-editor/blob/7c0ea7c452a8b52f5d2a76cb7377891270a4abfb/ios/Plugin/VideoEditor.swift#L98-L129

**Comment by CricketLaChica** [comment]
@dragermrb I've [opened a PR](https://github.com/dragermrb/capacitor-plugin-video-editor/pull/19). Hopefully, this helps!
