### ISSUE TITLE
No Result With MediaFileResult

### ISSUE THREAD

**Issue by prometeomcclellan** [dragermrb/capacitor-plugin-video-editor#20]
Hello. I'm trying to compress videos to low their size and be able to upload them to my server. I have installed and followed the documentation of yours. The thing is that when my code gets to the point of  MediaFileResult it just goes out of the function and I just can not get the result. 

So basically here is my code.

![Imagen 22-1-24 a las 5 01 p  m](https://github.com/dragermrb/capacitor-plugin-video-editor/assets/17907602/641f2ab5-85c4-4161-ace9-bf3c3176f38c)

**Comment by prometeomcclellan** [comment]
`$("#fileInputV").on("change", evt => {
      evt.preventDefault();
      evt.stopPropagation();
      evt.stopImmediatePropagation();
      const fileInputVs = (document.getElementById("fileInputV") as HTMLInputElement).files;
      console.dir(fileInputVs);
      this.isVideo = true;

      setTimeout(() => {
        if (fileInputVs.length > 0) {
          this.videosSeleccionados = fileInputVs.length;
          $("#imagenesConteo").fadeIn('xslow');
          $("#buttonSubmitVideo").fadeIn('xslow');
          
          for (let index = 0; index < fileInputVs.length; index++) {
            this.fechaFirma = new Date().toISOString();
            const file = fileInputVs[index];
            var path = (window.URL || window.webkitURL).createObjectURL(file);
            console.log('path', path);

            VideoEditor.edit({
              path: path.substring(12),
              transcode: {
                width: 720,
                height: 480,
                keepAspectRatio: true,
              },
              trim: {
                startsAt: 3 * 1000, // from 00:03
                endsAt: 10 * 1000, // to 00:10
              },
            }).then(
              (mediaFileResult: MediaFileResult) => {
            //    progressListener.remove();
            alert(parseInt(localStorage.getItem('idAtencion')))
                this.videos.push(mediaFileResult.file);
                this.videoArray = {
                  IdAtencion: parseInt(localStorage.getItem('idAtencion')),
                  VideoData: mediaFileResult.file
                }
  
                console.log('El comprimido ');
                console.dir(this.videoArray)


                console.log('mediaPath', mediaFileResult.file.path);
              },
              (error) => {
                console.error('error', error);
              }
            );

    
            if (index == (fileInputVs.length-1)) {
              this.isLoading = false
            }
            
          }
          
        }else{
        }
      }, this.randomIntFromInterval(1, 5));
    });
  }`

**Comment by dragermrb** [comment]
Hi @prometeomcclellan 

Could you attach the logcat (android) output?

Also add the line `console.log('mediaFileResult', mediaFileResult)` just before the `alert(...)` and show the output as well.

**Comment by prometeomcclellan** [comment]
Sure thing. And now I realize it's a matter of it seems not to work on Web but on devices only. Am I right? Sorry to bother. Let me give a try and test in a mobile device. 

![Imagen 23-1-24 a las 9 40 a  m](https://github.com/dragermrb/capacitor-plugin-video-editor/assets/17907602/f59b9706-2a16-4f15-94f6-cd44887144ca)

**Comment by dragermrb** [comment]
The `path` field must be a local path. It can optionally starts with `file://`, but in the previous example you use a `blob:http` and it is not valid.

**Comment by prometeomcclellan** [comment]
Ok. I tried that on Web the path.substring(11);  Let me give it a hit on mobile and I'll let you know. Thanks for your time.

**Comment by merbin2012** [comment]
Hi
Do you have any suggestion for converting to local path
Currently I can generate the following URLs

```
http://localhost/_capacitor_content_/com.android.providers.media.documents/document/video%3A1000123897
Or
content://com.android.providers.media.documents/document/video%3A1000123897
```

**Comment by dragermrb** [comment]
Hi!

Results from plugin `capacitor-plugin-file-picker` (https://github.com/dragermrb/capacitor-plugin-file-picker) are valid as path for `capacitor-plugin-video-editor`

**Comment by martinbertinat** [comment]
Hi @dragermrb ! Do you plan to release a new version of the file picker plugin with Capacitor 6 support? Thanks 🫶

**Comment by dragermrb** [comment]
@martinbertinat 

https://github.com/dragermrb/capacitor-plugin-file-picker/releases/tag/v6.0.1
