### ISSUE TITLE
 Invalid parameters Error for m4v videos

### ISSUE THREAD

**Issue by hamzawii** [dragermrb/capacitor-plugin-video-editor#21]
Hello, 

When i try to create a thumbnail or edit a video using this lib with a .m4v files as input i get the error on IOS :  Invalid parameters. 

mp4 videos works well.

Is there a way to fixe this ?

Thank you

**Comment by dragermrb** [comment]
Any error message on Xcode debug console?

**Comment by dragermrb** [comment]
Closed due to lack of response
