### ISSUE TITLE
Setting FPS

### ISSUE THREAD

**Issue by martinbertinat** [dragermrb/capacitor-plugin-video-editor#23]
Hi!.

I'm interested in knowing if it's possible to configure the frames per second (FPS) when editing videos. 

Thanks

**Comment by dragermrb** [comment]
Hi @martinbertinat 

Feature added! See transcode settings

https://github.com/dragermrb/capacitor-plugin-video-editor/releases/tag/v6.1.0

**Comment by martinbertinat** [comment]
Thanks @dragermrb. I'll be testing this the next week!
