### ISSUE TITLE
Android VideoEditor.edit on path like content:/.....

### ISSUE THREAD

**Issue by massimoliani** [dragermrb/capacitor-plugin-video-editor#24]
I'm trying to move from an old cordova plugin for video compression to your plugin.
iOS perfect everything is working.
On Android the picker result is content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F330/ORIGINAL/NONE/video%2Fmp4/1886352099 I pass it without uri component decode or with uri component deconde but the result is always error input file 

This is the call to the plugin 
<img width="932" alt="Screenshot 2024-07-26 alle 23 02 18" src="https://github.com/user-attachments/assets/20f32aec-5544-4117-b211-cb84f4bdb2f6">

And this the result:
<img width="920" alt="Screenshot 2024-07-26 alle 23 02 31" src="https://github.com/user-attachments/assets/0f6e915b-f122-4a23-9dee-c95ee2bdf735">

This the npx cap doctor result
Installed Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/ios: 5.7.4
  @capacitor/android: 5.7.4

Plugin version 5.0.6 as still using capacitor 5.

I found an error on capacitor, already issued to capacitor team, when trying a filesystem copy or stat on a content:/ path the android bridge crash.

Thanks for your support.

**Comment by dragermrb** [comment]
Hi @massimoliani 

The schema `content://` is not supported, you need to supply a local path to `edit()` method. You need copy the content of source file to a temporal file by your own before using it.

Alternatively, you can use this other plugin (https://github.com/dragermrb/capacitor-plugin-file-picker) to select the file.

**Comment by massimoliani** [comment]
I did a plugin to copy a content to local path like your file picker plugin.

*--------------------------*

dr. *Massimo Liani*

Goooled s.r.l.
Via Torricelli, 26
33080 - Porcia - PN

tel:3884484284


Il giorno ven 2 ago 2024 alle 12:22 Manuel Rodríguez <
***@***.***> ha scritto:

**Comment by coderpradp** [comment]
@massimoliani Would you be able to share the plugin. My application already makes extensive use of [@capawesome/capacitor-file-picker](https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/file-picker), so transitioning to [dragermrb/capacitor-plugin-file-picker](https://github.com/dragermrb/capacitor-plugin-file-picker) isn't feasible at this time.

Additionally, I’m unable to use both plugins concurrently as they are registered under the same name.

**Comment by massimoliani** [comment]
This is a small plugin for android to copy media store picked file to local
folder https://github.com/massimoliani/skirank-copy-android
For ios no problem picked files are already in app local folder.

*--------------------------*

dr. *Massimo Liani*

Goooled s.r.l.
Via Torricelli, 26
33080 - Porcia - PN

tel:3884484284


Il giorno sab 14 set 2024 alle ore 12:45 Pradip Khadka <
***@***.***> ha scritto:
