### ISSUE TITLE
Android Permission App Crash

### ISSUE THREAD

**Issue by danbunkr** [dragermrb/capacitor-plugin-video-editor#3]
Hey @dragermrb. We are using this plugin to generate thumbnail previews for movie / video files saved on a user's phone. It's working perfectly on iOS but there seems to be an issue on Android around permissions. 

The following is our code:

```
      const { value: devicePath } = await Preferences.get({
        key: storageKey,
      });

      if (devicePath) {
        const { uri } = await Filesystem.getUri({
          path: devicePath,
          directory: getDataDirectory(),
        });

        if (uri) {
          try {
            const { file } = await VideoEditor.thumbnail({
              path: normalizeVideoPath(uri),
              width: 600,
              height: 600,
              at: 0,
            });

            setFileThumbnail(Capacitor.convertFileSrc(file.path));
          } catch (error) {
            appInsights.trackException({
              exception: error,
              severityLevel: SeverityLevel.Error,
              properties: { name: 'thumbnail creation', fileId },
            });
          }
        }
```

And in out appInsights we are observing the following error after the Android app completely crashes.

```
Error: User denied access to storage
    at returnResult (http://localhost/:745:32)
    at win.androidBridge.onmessage (http://localhost/:720:21)
```

Potential Solution:
- Provide a method to check is permissions exist and then pass that responsibility onto the dev to check for permissions prior to triggering the thumbnail method.
- Allow the permission error to occur but allow the app to continue running (we are catching this error at the JS level and it's still crashing the app completely) 

Additional Note:
Adding `<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>` to the AndroidManifest.xml seems to help resolve it

**Comment by dragermrb** [comment]
Hi @danbunkr 

Can you attach logcat output?
