### ISSUE TITLE
Cannot read URI paths

### ISSUE THREAD

**Issue by caiorsantanna** [dragermrb/capacitor-plugin-video-editor#4]
I have the following use case:

I get the file path using the video picker
I need to optimize the file so that I can upload it faster
I use a capacitor plugin to reduce the size of the video
This plugin returns an error because it cannot find the file path ;(

```
      const result = await FilePicker.pickVideos({
        readData: true
      });

      const video = result?.files[0];
      if (!video.path) { return null; }

      const configurations = await this.configurationsService.getConfigurations();

      VideoEditor.addListener('transcodeProgress', (info) => {
        console.log(info.progress);
      });

      const editResult = await VideoEditor.edit({
        path: video.path,
        transcode: {
          height: configurations.pictureHeight,
          width: configurations.pictureWidth,
          keepAspectRatio: true
        }
      });
```

![image](https://user-images.githubusercontent.com/26316189/225490258-048d4791-10b3-461c-934b-7a336023ecf4.png)

Related: https://github.com/capawesome-team/capacitor-plugins/issues/11

**Comment by dragermrb** [comment]
I think it is related to the path format.

Can you try another file-picker like this https://github.com/dragermrb/capacitor-plugin-file-picker?
