### ISSUE TITLE
MOV to mp4 transcode

### ISSUE THREAD

**Issue by bmunavarbasha** [dragermrb/capacitor-plugin-video-editor#7]
I am trying to transcode mov video on ios to mp4. there is no mime-type or format parameter on transcode options, Is it available? 

Is it something you will add?

**Comment by dragermrb** [comment]
Hi @bmunavarbasha 

This plugin always produce a MP4 file as result. You can use any IOS compatible video file as source.

**Comment by bmunavarbasha** [comment]
okay great thank you!
